---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datauser
  namespace: longhorn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: datauser
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: datauser
    spec:
      containers:
        - name: web-server
          image: nginx
          volumeMounts:
            - name: data
              mountPath: /var/lib/www
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
            readOnly: false

...