---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: longhorn
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: longhorn

...